### PR TITLE
Make pyang a library content

### PR DESCRIPTION
**Pull request by miroslavKovacPantheon**
We should not assume that user will have
installed pyang but rather we need to use
pyang public api that will allow us to
parse the module and get the revision

Signed-off-by: miroslav.kovac <miroslav.kovac@pantheon.tech>

### CODE REVIEW

**Review by einarnn — COMMENTED** [review]
I don't understand why you have pasted in a whole bunch of content from the pyang module into this "pyangHelper" sub-directory. Haven't reviewed the code in detail, but can you explain why just using pyang's public API isn't good enough and why the content your file `default_statements.py` needed to b e copied in from pyang?

**Review by einarnn — COMMENTED** [review]
Also, by introducing the pyang dependency in requirements.txt, you _should_ be ensuring that pyang is available on the path in the environment xym is running in, as well as having the livrary available.

**Comment by miroslavKovacPantheon** [comment]
> 
> 
> I don't understand why you have pasted in a whole bunch of content from the pyang module into this "pyangHelper" sub-directory. Haven't reviewed the code in detail, but can you explain why just using pyang's public API isn't good enough and why the content your file `default_statements.py` needed to b e copied in from pyang?

**Comment by miroslavKovacPantheon** [comment]
accidentally closed -> opened new PR here -> https://github.com/xym-tool/xym/pull/43

**Pull request closed without merging**
