### PR TITLE
Add support for RFCXMLv3

### PR DESCRIPTION
**Pull request by richardzilincikPantheon**
Add an `--rfcxml` flag for extracting YANG modules from I-Ds and RFCs in RFCXML v3 format.

### CODE REVIEW

**Review by einarnn — APPROVED** [review]

**Comment by einarnn** [comment]
@richardzilincikPantheon, can you resolve the merge conflicts by bringing this PR up to date with the main line?

**Review by einarnn — CHANGES_REQUESTED** [review]
Please merge latest main line changes.

**Comment by einarnn** [comment]
@richardzilincikPantheon, @SlavomirMazurPantheon -- Please check this PR against updated mainline. There are conflicts which I cannot resolve easily.

**Comment by richardzilincikPantheon** [comment]
Hi @einarnn, sorry to keep you waiting, all resolved.

**Review by einarnn — APPROVED** [review]

**Pull request merged**
